allow specification of facets in EIA.get_dataset
kmax12/gridstatus pull request #273
Opened 2023-09-14 18:33 UTC by JMorganUSU

Minor change to allow specification of facets in get_dataset function for EIA. I'm trying to get generation data for one balancing authority, so being able to include the facets I care about in get_dataset allows me to only request data for the one, instead of getting all BAs then throwing away most of the data. facets is an optional parameter, ensuring backwards compatibility with previous versions.

2023-09-14 20:19 UTC, kmax12 requested changes
thanks! other than one comment the only thing missing a test. you can define that in test_eia.py

2023-09-14 20:19 UTC, kmax12 commented on gridstatus/eia.py
> +    def get_dataset(self, dataset, start, end, facets={}, n_workers=1, verbose=False):
Using mutable default arguments like facets={} is risky in Python. The default value is shared across all calls to the function. If facets is modified in one call, the modified value will be used in subsequent calls, leading to unexpected behavior.

Use None and set to a new dictionary inside the function instead:

```python
def get_dataset(self, dataset, start, end, facets=None, n_workers=1, verbose=False):
    if facets is None:
        facets = {}
```

This way, a new dictionary is created for each function call, avoiding the shared state issue.

2024-01-19 01:22 UTC, JMorganUSU commented
Made requested changes, including adding a test (which passes) and updating the changelog.

2024-02-05 01:35 UTC, WillKoehrsen commented
If the build passes, this should be ready to merge. There is a minor conflict in `CHANGELOG.md` that needs to be fixed after merging the latest `main` into the PR branch.

2024-02-12 22:23 UTC, JMorganUSU commented
Are any other changes needed or is this ready to merge?

2024-02-12 22:56 UTC, WillKoehrsen approved these changes
👍🏽 Thanks for the contribution!

2024-02-12 22:57 UTC, merged